-- MySQL Script generated by MySQL Workbench
-- Thu Dec  3 03:09:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `loja` ;

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja` DEFAULT CHARACTER SET utf8 ;
USE `loja` ;

-- -----------------------------------------------------
-- Table `loja`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `loja`.`CLIENTE` (
  `codCliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(11) NULL,
  `status` TINYINT NULL,
  `dataNascimento` DATE NULL,
  PRIMARY KEY (`codCliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`FORNECEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`FORNECEDOR` ;

CREATE TABLE IF NOT EXISTS `loja`.`FORNECEDOR` (
  `codFornecedor` INT NOT NULL,
  `nomeFantasia` VARCHAR(45) NULL,
  `razaoSocial` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`codFornecedor`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`PRODUTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`PRODUTO` ;

CREATE TABLE IF NOT EXISTS `loja`.`PRODUTO` (
  `codProduto` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `precoUnitario` DECIMAL(5,2) NULL,
  `status` TINYINT NULL,
  `FORNECEDOR_codFornecedor` INT NOT NULL,
  PRIMARY KEY (`codProduto`),
  INDEX `fk_PRODUTO_FORNECEDOR_idx` (`FORNECEDOR_codFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTO_FORNECEDOR`
    FOREIGN KEY (`FORNECEDOR_codFornecedor`)
    REFERENCES `loja`.`FORNECEDOR` (`codFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`VENDA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`VENDA` ;

CREATE TABLE IF NOT EXISTS `loja`.`VENDA` (
  `codVenda` INT NOT NULL,
  `dataHora` DATETIME NOT NULL,
  `status` TINYINT NOT NULL,
  `valor` DECIMAL(5,2) NOT NULL,
  `CLIENTE_codCliente` INT NOT NULL,
  `PRODUTO_codProduto` INT NOT NULL,
  PRIMARY KEY (`codVenda`),
  INDEX `fk_Venda_CLIENTE1_idx` (`CLIENTE_codCliente` ASC) VISIBLE,
  INDEX `fk_Venda_PRODUTO1_idx` (`PRODUTO_codProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_CLIENTE1`
    FOREIGN KEY (`CLIENTE_codCliente`)
    REFERENCES `loja`.`CLIENTE` (`codCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_PRODUTO1`
    FOREIGN KEY (`PRODUTO_codProduto`)
    REFERENCES `loja`.`PRODUTO` (`codProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
